### ISSUE TITLE
Begin DB creation

### ISSUE THREAD

**Issue by jp-braun** [uwasystemhealth/FRACAS_Team1#11]
Create database using PostgreSQL and Amazon RDS

**Comment by VictorAZ12** [comment]
Created a database using AWS RDS. The database is running and will be used to implement FRACAS database. Snapshot/backup policies are planned.
Database specs:
- Engine: PostgreSQL
- Class: db.t3.micro
- Region & AZ: ap-southeast-2a
- Connection: TCP port 5432 (postgres)
- Connection details: ask VictorAZ12 (Yanchen Zhao) for connection details.
