### ISSUE TITLE
Initiate server

### ISSUE THREAD

**Issue by jp-braun** [uwasystemhealth/FRACAS_Team1#13]
Get the backend started with AWS

**Comment by VictorAZ12** [comment]
Initiated an EC2 instance which can be used as the web server.
[Tutorial used](https://www.programink.com/django-tutorial/django-deployment.html)
Instance specs:

- Instance type: t2.micro
- Storage: 8 GB EBS
- Security: A security group which only allows SSH connection (for the developers' connections only)
- Key pair: A .pem key file. Please contact VictorAZ12 (Yanchen Zhao) for the key file.
