### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by jp-braun** [uwasystemhealth/FRACAS_Team1#33]
Team effort for final deployment.

**Comment by VictorAZ12** [comment]
A possible solution: deploy backend/frontend on an EC2 instance, then use Amazon 53 to configure domain name and routing, etc.

**Comment by VictorAZ12** [comment]
[A reference blog](https://mattsegal.dev/django-spa-infrastructure.html), feel free to add more options and reference here

**Comment by VictorAZ12** [comment]
Note: some of the steps are already done.
SSH host: ec2-3-27-164-241.ap-southeast-2.compute.amazonaws.com
Private key: contact Yanchen for key file (uploaded in chat group)

### Backend deployment on an EC2 instance
1. Launch an AWS EC2 instance with a Linux AMI
2. Configure security groups to allow SSH, HTTP, and custom TCP connection port 8000.
3. SSH into the AWS EC2 instance, login with user name `ubuntu` and the key file (contact admin for access).
4. Perform steps 1-11 in local running of the server.
5. Run server with `python3 manage.py runserver 0.0.0.0:8000`.
6. Access the server using EC2 instace's public address (currently assigned with 3.27.164.241) combined with the port number 8000.

**Comment by VictorAZ12** [comment]
# Deployment Test 2
Deployed frontend as static webpage at a [github page](https://victoraz12.github.io/FRACAS_Deployed/).
Backend needs to be configured with a HTTPS-protected web server.

Backend configuration progress:

- [x] Nginx configuration
- [x] Gunicorn socket configuration
- [x] Nginx Internal test
- [ ] Reverse proxy
- [ ] Accessible via the Internet
