### ISSUE TITLE
Search/filter Page Development

### ISSUE THREAD

**Issue by sj9612** [uwasystemhealth/FRACAS_Team1#52]
- Develop the page for searching the records.
- Integrate the API for the same

**Comment by VictorAZ12** [comment]
Added subsystem and car year filters in the search page. Worked just as the team filter.

**Comment by VictorAZ12** [comment]
Added pagination for results.

**Comment by VictorAZ12** [comment]
Date filter (start date/end date), creator filter are needed

**Comment by VictorAZ12** [comment]
Statuses filters are needed
