### ISSUE TITLE
Responsive Navbar

### ISSUE THREAD

**Issue by jp-braun** [uwasystemhealth/FRACAS_Team1#54]
Responds to isTeamLead and authentication

**Comment by jp-braun** [comment]
Also need a new report button in the Nav. Requirement to have 'one-click' reporting.

**Comment by VictorAZ12** [comment]
Responsive to admin privilege added in commit 2978991.
Responsive to mobile added in commit 14044f1.

**Comment by VictorAZ12** [comment]
> Also need a new report button in the Nav. Requirement to have 'one-click' reporting.

Moved to #89
