### ISSUE TITLE
Forgotten password email - backend

### ISSUE THREAD

**Issue by jp-braun** [uwasystemhealth/FRACAS_Team1#56]
Implement email verification as well?

**Comment by jp-braun** [comment]
Currently working in backend-email branch with the package Djoser. Will require a few more pages for email verification conformation, forgotten password reset, etc
.

**Comment by VictorAZ12** [comment]
if it's easier to do authentication with Djoser then I'd like to give it a try.

> Currently working in backend-email branch with the package Djoser. Will require a few more pages for email verification conformation, forgotten password reset, etc. Djoser replaces a lot of authentication as well...

**Comment by jp-braun** [comment]
closed with djoser integration
