### ISSUE TITLE
User-specific record editing permissions

### ISSUE THREAD

**Issue by jp-braun** [uwasystemhealth/FRACAS_Team1#66]
Allow specific records to be edited by a selectable list of users

**Comment by VictorAZ12** [comment]
Backend functionality only: record owners should be a list of users (store the user_id).

**Comment by VictorAZ12** [comment]
Also, the review status should be modifiable only by admins (as required by the clients).

**Comment by jp-braun** [comment]
Can we add a permission to allow teams to be read without authentication, for the registration page?

**Comment by VictorAZ12** [comment]
`record_editors = models.ManyToManyField(User, blank=True)` is added to the record model to store a list of users that can edit a record instance. A string of unlinked user names cannot be created upon the creation, as the ManyToManyField only works with a record_id that is generated after the creation.
