### ISSUE TITLE
Add a report button in the Nav

### ISSUE THREAD

**Issue by VictorAZ12** [uwasystemhealth/FRACAS_Team1#89]
Need a new report button in the Nav. Requirement to have 'one-click' reporting.

_Originally posted by @jp-braun in https://github.com/uwasystemhealth/FRACAS_Team1/issues/54#issuecomment-1738462584_

**Comment by jp-braun** [comment]
might as well put new reports & search in the nav and just get rid of the dashboard. logout is already in the nav.

**Comment by jp-braun** [comment]
Dashboard renamed menu to take less space. Can be eliminated, will ask client's preference.
